name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Check out unity project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Unity Version
        id: getUnityVersion
        uses: appegy/unity-version-action@v3
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v4
        with:
          unityVersion: ${{ steps.getUnityVersion.outputs.unity-version }}
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
